portfolio:
  tickers: [NVDA, AMD, QCOM, INTC, MU, TXN, TSM, ASML, NXPI, AAPL, MSFT]
  start_date: '2019-01-01'
  end_date: '2024-01-01'
  weights: null
  frequency: 'D'
  use_cache: true
  include_macro: true
  macro_tickers: ['^VIX', '^TNX', '^TYX']

regime:
  n_regimes: 3
  n_iter: 2000
  random_state: 42
  window_size: 63
  # Features must match those created in get_portfolio_features_with_macro:
  # 'returns', 'volatility', 'momentum', 'skewness', 'kurtosis',
  # '^tyx_yield', '^tyx_yield_ma', '^tyx_yield_spread'
  features:
    - returns
    - volatility
    - momentum
    - skewness
    - kurtosis
  min_regime_size: 21
  smoothing_window: 7
  use_deep_learning: true
  alert_threshold: 0.7
  min_confidence: 0.6
  update_frequency: '1D'
  history_size: 100

deep_learning:
  sequence_length: 20
  hidden_dims: [64, 32, 16]
  epochs: 100
  learning_rate: 0.0005
  dropout_rate: 0.3
  use_attention: true
  bidirectional: true
  residual_connections: true
  batch_normalization: true
  l2_regularization: 0.001
  gradient_clipping: 1.0
  validation_split: 0.2
  early_stopping_patience: 20
  learning_rate_schedule:
    type: cosine_annealing
    T_max: 30
    eta_min: 0.00001

risk:
  confidence_level: 0.95
  max_drawdown_limit: 0.10
  volatility_target: 0.15
  stop_loss: 0.02
  take_profit: 0.50
  var_calculation_method: historical
  es_calculation_method: historical
  regime_detection_method: volatility
  stress_scenarios: [2008_crisis, covid_crash, tech_bubble]
  correlation_regime: true
  tail_risk_measure: evt

monte_carlo:
  n_sims: 10000
  n_days: 1260  # 5 years
  risk_free_rate: 0.05
  confidence_levels: [0.05, 0.25, 0.5, 0.75, 0.95]
  distribution: t
  simulation_mode: block_bootstrap

backtest:
  initial_cash: 100000
  transaction_cost: 0.001
  position_sizing: regime_confidence
  confidence_threshold: 0.8
  max_position_size: 1.0
  base_position_size: 0.5
  rebalance_freq: 'D'
  stop_loss: 0.02
  take_profit: 0.30
  max_drawdown: 0.10
  allow_short: true
  min_trade_size: 1e-6
